import { isTrustedOrigin } from "../security/origin.js";
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";
import type { AuthService } from "../auth/authService.js";
import type { AuthenticatedUser } from "../auth/authorization.js";
import { SESSION_COOKIE_NAME } from "./auth.js";
import { RegionalCommissionService } from "../regionalCommissions/regionalCommissionService.js";

const user = async (request: FastifyRequest, reply: FastifyReply, auth: AuthService): Promise<AuthenticatedUser | null> => { const token = request.cookies?.[SESSION_COOKIE_NAME]; const actor = token ? await auth.getSessionUser(token) : null; if (!actor) { void reply.status(401).send({ error: "请先登录" }); return null; } return actor; };
export const registerRegionalCommissionRoutes = async (app: FastifyInstance, options: { authService: AuthService; service: RegionalCommissionService; appOrigin: string }): Promise<void> => {
  app.addHook("preHandler", async (request, reply) => {
    if (request.url.startsWith("/api/regional-commissions") || request.url.startsWith("/api/admin/regional-commission")) {
      if (request.method !== "GET" && request.headers.origin && !isTrustedOrigin(request.headers.origin, options.appOrigin)) {
        return reply.status(403).send({ error: "请求来源不可信" });
      }
    }
  });
  app.get("/api/regional-commissions/managers", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; try { return { items: await options.service.listManagers(actor) }; } catch (e) { return reply.status(403).send({ error: e instanceof Error ? e.message : "无权访问" }); } });
  app.get<{ Querystring: { managerId: string } }>("/api/regional-commissions/target-plans", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; try { return { items: await options.service.listTargetPlans(actor, request.query.managerId) }; } catch (e) { return reply.status(403).send({ error: e instanceof Error ? e.message : "无权访问" }); } });
  app.post("/api/regional-commissions/target-plans/suggest", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ managerId: z.string().min(1), reason: z.string().trim().min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请检查大区经理和创建原因" }); try { return reply.status(201).send(await options.service.createSuggestedTargetPlan(actor, parsed.data.managerId, parsed.data.reason)); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "创建失败" }); } });
  app.post("/api/regional-commissions/target-plans", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ id: z.string().optional(), managerId: z.string().min(1), planType: z.enum(["quarter", "half_year", "year"]), startsOn: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), periodTargets: z.array(z.number().int().positive()), reason: z.string().trim().min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请检查计划类型、开始日期、各期目标和设置原因" }); try { return reply.status(parsed.data.id ? 200 : 201).send(await options.service.saveTargetPlanDraft(actor, parsed.data)); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "保存失败" }); } });
  app.post<{ Params: { id: string } }>("/api/regional-commissions/target-plans/:id/activate", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ reason: z.string().trim().min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请填写启用原因" }); try { return await options.service.activateTargetPlan(actor, request.params.id, parsed.data.reason); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "启用失败" }); } });
  app.get("/api/admin/regional-commission-templates", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; try { return { items: await options.service.listTemplates(actor) }; } catch (e) { return reply.status(403).send({ error: e instanceof Error ? e.message : "无权访问" }); } });
  app.post("/api/admin/regional-commission-templates", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ name: z.string().min(1), effectiveFrom: z.string(), reason: z.string().min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请检查模板信息" }); try { return reply.status(201).send(await options.service.createTemplate(actor, parsed.data)); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "保存失败" }); } });
  app.post<{ Params: { id: string } }>("/api/admin/regional-commission-templates/:id/copy", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ name: z.string().optional(), effectiveFrom: z.string(), reason: z.string().min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请检查模板信息" }); try { return reply.status(201).send(await options.service.copyTemplate(actor, request.params.id, parsed.data)); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "复制失败" }); } });
  app.post<{ Params: { id: string } }>("/api/admin/regional-commission-templates/:id/publish", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ reason: z.string().min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请填写发布原因" }); try { return await options.service.publishTemplate(actor, request.params.id, parsed.data.reason); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "发布失败" }); } });
  app.patch<{ Params: { id: string } }>("/api/admin/regional-commission-templates/:id", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ rules: z.record(z.string(), z.unknown()), reason: z.string().min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请检查模板规则" }); try { return await options.service.updateTemplate(actor, request.params.id, parsed.data.rules as never, parsed.data.reason); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "修改失败" }); } });
  app.post<{ Params: { id: string } }>("/api/admin/regional-commission-templates/:id/stop", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ reason: z.string().min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请填写停用原因" }); try { return await options.service.stopTemplate(actor, request.params.id, parsed.data.reason); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "停用失败" }); } });
  app.post("/api/admin/regional-commission-assignments", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ managerId: z.string(), templateVersionId: z.string(), effectiveFrom: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), reason: z.string().trim().min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请检查大区经理、模板、分配生效日期和操作原因" }); try { await options.service.assignTemplate(actor, parsed.data); return { ok: true }; } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "分配失败" }); } });
  app.get<{ Querystring: { managerId?: string; month?: string } }>("/api/regional-commissions/summary", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const managerId = request.query.managerId ?? actor.id; try { return await options.service.summary(actor, managerId, request.query.month); } catch (e) { return reply.status(403).send({ error: e instanceof Error ? e.message : "无权访问" }); } });
  app.get<{ Querystring: { managerId: string } }>("/api/regional-commissions/personal-orders", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; return { items: await options.service.listPersonalOrders(actor, request.query.managerId) }; });
  app.post("/api/regional-commissions/receipts", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ managerId: z.string(), month: z.string().regex(/^\d{4}-\d{2}$/), netReceiptFen: z.number().int(), evidenceNo: z.string().trim().min(1), note: z.string().optional() }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请检查净回款" }); try { return reply.status(201).send({ id: await options.service.upsertReceipt(actor, parsed.data) }); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "保存失败" }); } });
  app.post("/api/regional-commissions/personal-orders", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ managerId: z.string(), orderNo: z.string().min(1), channel: z.string().min(1), orderCount: z.number().int().positive(), businessDate: z.string(), signedOn: z.string(), evidenceNo: z.string().min(1), note: z.string().optional(), lines: z.array(z.object({ sku: z.enum(["WATCH", "MATTRESS", "GATEWAY", "MOTION", "DOOR", "PORTABLE_BUTTON", "WALL_BUTTON"]), label: z.string(), quantity: z.number().int().positive() })).min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请检查个人渠道订单" }); try { return reply.status(201).send(await options.service.createPersonalOrder(actor, parsed.data)); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "保存失败" }); } });
  app.post<{ Params: { id: string } }>("/api/regional-commissions/personal-orders/:id/return", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ completedOn: z.string(), reason: z.string().min(1), lines: z.array(z.object({ lineId: z.string(), returnedQuantity: z.number().int().nonnegative() })).min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请检查退货信息" }); try { await options.service.returnPersonalOrder(actor, request.params.id, parsed.data); return { ok: true }; } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "退货登记失败" }); } });
  app.post<{ Params: { id: string } }>("/api/regional-commissions/personal-orders/:id/void", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ reason: z.string().min(1) }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "作废必须填写原因" }); try { await options.service.voidPersonalOrder(actor, request.params.id, parsed.data.reason); return { ok: true }; } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "作废失败" }); } });
  app.post<{ Params: { id: string } }>("/api/regional-commissions/receipts/:id/verify", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ approved: z.boolean(), reason: z.string().optional() }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请检查核验信息" }); try { await options.service.verifyReceipt(actor, request.params.id, parsed.data.approved, parsed.data.reason); return { ok: true }; } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "核验失败" }); } });
  app.get<{ Querystring: { managerId: string } }>("/api/regional-commissions/cooperation", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; return { items: await options.service.listCooperation(actor, request.query.managerId) }; });
  app.post("/api/regional-commissions/cooperation", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const parsed = z.object({ managerId: z.string(), stageCode: z.string(), achievedOn: z.string(), evidenceNo: z.string().min(1), note: z.string().optional() }).safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: "请检查合作奖资料" }); try { return reply.status(201).send(await options.service.submitCooperation(actor, parsed.data)); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "保存失败" }); } });
  app.post<{ Params: { id: string; action: "verify" | "confirm" | "revoke" } }>("/api/regional-commissions/cooperation/:id/:action", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; const body = z.object({ reason: z.string().optional() }).parse(request.body ?? {}); try { await options.service.transitionCooperation(actor, request.params.id, request.params.action, body.reason); return { ok: true }; } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "操作失败" }); } });
  app.post<{ Params: { managerId: string; month: string } }>("/api/regional-commissions/statements/:managerId/:month/calculate", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; try { return await options.service.calculateStatement(actor, request.params.managerId, request.params.month); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "计算失败" }); } });
  app.get<{ Querystring: { managerId: string } }>("/api/regional-commissions/statements", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; return { items: await options.service.listStatements(actor, request.query.managerId) }; });
  app.post<{ Params: { id: string; action: "confirm" | "pay" } }>("/api/regional-commissions/statements/:id/:action", async (request, reply) => { const actor = await user(request, reply, options.authService); if (!actor) return; try { return await options.service.transitionStatement(actor, request.params.id, request.params.action); } catch (e) { return reply.status(400).send({ error: e instanceof Error ? e.message : "操作失败" }); } });
};
