import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import type { ApiClient, AuthenticatedUser, RegionalCommissionSummary, RegionalManagerOption, RegionalStatementDto, RegionalTemplateDto } from "../api/client";
import { PageLayout } from "../components/layout";
import "./regionalCommission.css";

const yuan = (fen: number) => `¥${(fen / 100).toFixed(2)}`;
export const RegionalCommissionPage = ({ client, actor }: { client: ApiClient; actor: AuthenticatedUser }) => {
  const [workspace, setWorkspace] = useState("targets");
  const [managers, setManagers] = useState<readonly RegionalManagerOption[]>([]);
  const [managerId, setManagerId] = useState(actor.role === "regional_manager" ? actor.id : "");
  const [summary, setSummary] = useState<RegionalCommissionSummary | null>(null);
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [message, setMessage] = useState<string | null>(null);
  const [templates, setTemplates] = useState<readonly RegionalTemplateDto[]>([]);
  const [statements, setStatements] = useState<readonly RegionalStatementDto[]>([]);
  const [receiptForm, setReceiptForm] = useState({ amountYuan: "", evidenceNo: "" });
  const [cooperationForm, setCooperationForm] = useState({ stageCode: "PROJECT", achievedOn: "", evidenceNo: "" });
  const [templateForm, setTemplateForm] = useState({ name: "海南大区经理提成", effectiveFrom: new Date().toISOString().slice(0, 10) });
  const [planForm, setPlanForm] = useState({ planType: "half_year" as "quarter" | "half_year" | "year", startsOn: "", targets: "1000,4000,8000,10000,13000,14000" });
  const load = () => { if (!managerId) return; void Promise.all([client.getRegionalCommissionSummary({ managerId, month }), client.listRegionalStatements(managerId)]).then(([current, currentStatements]) => { setSummary(current); setStatements(currentStatements); if (current.planId && current.periods.length) setPlanForm((value) => ({ ...value, planType: current.periods.length === 3 ? "quarter" : current.periods.length === 12 ? "year" : "half_year", startsOn: current.periods[0]!.startsOn, targets: current.periods.map((period) => String(period.targetOrderCount)).join(",") })); setMessage(null); }).catch((e) => setMessage(e instanceof Error ? e.message : "加载失败")); };
  useEffect(() => { if (actor.role !== "regional_manager") void client.listRegionalManagers().then(setManagers).catch(() => undefined); if (actor.role === "admin") void client.listRegionalTemplates().then(setTemplates).catch(() => undefined); }, [actor.role, client]);
  useEffect(() => { const selected = managers.find((manager) => manager.id === managerId); if (selected?.employmentStartDate) setPlanForm((value) => ({ ...value, startsOn: selected.employmentStartDate! })); }, [managerId, managers]);
  useEffect(() => { load(); }, [managerId, month]);
  const canEdit = actor.role === "hr" || actor.role === "admin";
  const run = async (action: () => Promise<unknown>, success: string) => { try { await action(); setMessage(success); load(); if (actor.role === "admin") void client.listRegionalTemplates().then(setTemplates); } catch (e) { setMessage(e instanceof Error ? e.message : "操作失败"); } };
  const planCount = planForm.planType === "quarter" ? 3 : planForm.planType === "half_year" ? 6 : 12;
  const savePlan = () => { const targets = planForm.targets.split(",").map((value) => Number(value.trim())); const input = { managerId, planType: planForm.planType, startsOn: planForm.startsOn, targets, reason: summary?.planId ? "HR修改大区经理目标计划" : "HR设置大区经理目标计划" }; void run(() => summary?.planId ? client.updateRegionalTargetPlan(summary.planId, input) : client.createRegionalTargetPlan(input), summary?.planId ? "目标计划已修改" : "目标计划已保存"); };
  return <PageLayout eyebrow="大区经理" title="大区经理提成" description="按签收满 7 天的有效订单和已核验业务数据计算。" actions={canEdit ? <Link className="regional-primary-action" to="/commissions/regional/personal-orders">录入个人渠道订单</Link> : undefined}>
    {(actor.role !== "regional_manager") ? <label className="regional-manager-select"><span>大区经理</span><select value={managerId} onChange={(e) => setManagerId(e.currentTarget.value)}><option value="">请选择</option>{managers.map((manager) => <option key={manager.id} value={manager.id}>{manager.displayName}（{manager.workNo}）</option>)}</select></label> : null}
    <div className="regional-toolbar"><label><span>结算月份</span><input type="month" value={month} onChange={(e) => setMonth(e.currentTarget.value)} /></label><button type="button" onClick={load}>刷新</button></div>
    {message ? <div className="system-notice" role="status">{message}</div> : null}
    {summary ? <>
      <nav className="ops-tabs regional-workspaces" aria-label="提成业务区域">
        {[["targets", "目标计划"], ...(actor.role !== "regional_manager" ? [["receipts", "回款核验"]] : []), ["cooperation", "合作奖"], ...(actor.role !== "regional_manager" ? [["statements", "工资提成单"]] : []), ...(actor.role === "admin" ? [["templates", "提成模板"]] : [])].map(([value, label]) => <button key={value} type="button" aria-pressed={workspace === value} onClick={() => setWorkspace(value!)}>{label}</button>)}
      </nav>
      <section className="regional-summary-grid" aria-label="提成汇总">{[["有效订单", `${summary.orderCount} 笔`], ["周期目标奖", yuan(summary.completionFen)], ["分段订单奖", yuan(summary.tieredOrderFen)], ["里程碑奖", yuan(summary.milestoneFen)], ["补足奖", yuan(summary.topUpFen)], ["回款加速奖", yuan(summary.revenueAccelerationFen)], ["个人商品提成", yuan(summary.personalProductFen)], ["合作奖", yuan(summary.cooperationFen)], ["累计金额", yuan(summary.totalFen)]].map(([label, value]) => <div className="regional-metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
      <section className="regional-section" hidden={workspace !== "targets"}><div className="regional-section-heading"><h2>目标周期</h2><span>营业厅 {summary.managedOrderCount} 笔 · 个人渠道 {summary.personalOrderCount} 笔</span></div><div className="regional-table-wrap"><table><thead><tr><th>周期</th><th>起止日期</th><th>目标</th><th>有效订单</th><th>目标奖</th></tr></thead><tbody>{summary.periods.map((period) => <tr key={period.sequence}><td>M{period.sequence}</td><td>{period.startsOn} 至 {period.endsOn}</td><td>{period.targetOrderCount}</td><td>{period.orderCount}</td><td>{yuan(period.rewardFen)}</td></tr>)}</tbody></table></div></section>
      {(actor.role === "hr" || actor.role === "admin") ? <section className="regional-section" hidden={workspace !== "targets"}><h2>设置目标计划</h2><div className="regional-entry-grid"><label><span>计划类型</span><select value={planForm.planType} onChange={(event) => { const planType = event.currentTarget.value as typeof planForm.planType; setPlanForm((value) => ({ ...value, planType, targets: planType === "quarter" ? "1000,4000,8000" : planType === "half_year" ? "1000,4000,8000,10000,13000,14000" : Array.from({ length: 12 }, () => 1000).join(",") })); }}><option value="quarter">季度（3期）</option><option value="half_year">半年（6期）</option><option value="year">全年（12期）</option></select></label><label><span>计划开始日期</span><input type="date" value={planForm.startsOn} onChange={(event) => { const startsOn = event.currentTarget.value; setPlanForm((value) => ({ ...value, startsOn })); }} /></label><label className="regional-targets-field"><span>各期目标（逗号分隔，共 {planCount} 个）</span><input value={planForm.targets} onChange={(event) => { const targets = event.currentTarget.value; setPlanForm((value) => ({ ...value, targets })); }} /></label><button type="button" onClick={savePlan}>保存目标计划</button></div></section> : null}
      {actor.role !== "regional_manager" ? <section className="regional-section" hidden={workspace !== "receipts"}><h2>不含税净回款</h2><div className="regional-entry-grid"><label><span>金额（元）</span><input type="number" value={receiptForm.amountYuan} onChange={(event) => { const amountYuan = event.currentTarget.value; setReceiptForm((value) => ({ ...value, amountYuan })); }} /></label><label><span>凭据编号</span><input value={receiptForm.evidenceNo} onChange={(event) => { const evidenceNo = event.currentTarget.value; setReceiptForm((value) => ({ ...value, evidenceNo })); }} /></label><button type="button" onClick={() => void run(() => client.saveRegionalReceipt({ managerId, month, netReceiptFen: Math.round(Number(receiptForm.amountYuan) * 100), evidenceNo: receiptForm.evidenceNo }), "净回款已保存，等待财务核验")}>保存回款</button>{summary.receipt && (actor.role === "finance" || actor.role === "admin") ? <button type="button" onClick={() => void run(() => client.verifyRegionalReceipt(summary.receipt!.id, true), "净回款已核验")}>核验通过</button> : null}</div></section> : null}
      {(actor.role === "hr" || actor.role === "admin") ? <section className="regional-section" hidden={workspace !== "cooperation"}><h2>海南电信合作奖</h2><div className="regional-entry-grid"><label><span>阶段</span><select value={cooperationForm.stageCode} onChange={(event) => { const stageCode = event.currentTarget.value; setCooperationForm((value) => ({ ...value, stageCode })); }}><option value="PROJECT">省级项目立项</option><option value="CONTRACT">商务签约及系统准入</option><option value="PILOT">首批试点上线</option><option value="SCALE">规模验证</option></select></label><label><span>达成日期</span><input type="date" value={cooperationForm.achievedOn} onChange={(event) => { const achievedOn = event.currentTarget.value; setCooperationForm((value) => ({ ...value, achievedOn })); }} /></label><label><span>凭据编号</span><input value={cooperationForm.evidenceNo} onChange={(event) => { const evidenceNo = event.currentTarget.value; setCooperationForm((value) => ({ ...value, evidenceNo })); }} /></label><button type="button" onClick={() => void run(() => client.submitRegionalCooperation({ managerId, ...cooperationForm }), "合作奖资料已提交")}>提交资料</button></div></section> : null}
      {<section className="regional-section" hidden={workspace !== "cooperation"}><h2>合作奖进度</h2><div className="regional-table-wrap"><table><thead><tr><th>阶段</th><th>达成日期</th><th>金额</th><th>状态</th><th>操作</th></tr></thead><tbody>{summary.cooperation.map((stage) => <tr key={stage.id}><td>{stage.stageLabel}</td><td>{stage.achievedOn}</td><td>{yuan(stage.amountFen)}</td><td>{stage.status}</td><td>{(actor.role === "finance" || actor.role === "admin") && stage.status === "submitted" && ["PILOT", "SCALE"].includes(stage.stageCode) ? <button type="button" onClick={() => void run(() => client.transitionRegionalCooperation(stage.id, "verify"), "阶段已核验")}>财务核验</button> : null}{actor.role === "admin" && (stage.status === "submitted" || stage.status === "finance_verified") ? <button type="button" onClick={() => void run(() => client.transitionRegionalCooperation(stage.id, "confirm"), "阶段奖励已确认")}>确认奖励</button> : null}</td></tr>)}</tbody></table></div>{summary.cooperation.length === 0 ? <p className="regional-empty">暂无合作奖记录</p> : null}</section>}
      {(actor.role === "hr" || actor.role === "admin" || actor.role === "finance") ? <section className="regional-section" hidden={workspace !== "statements"}><div className="regional-section-heading"><h2>工资提成单</h2>{actor.role !== "finance" ? <button type="button" onClick={() => void run(() => client.calculateRegionalStatement(managerId, month), "提成单已生成")}>计算本月提成单</button> : null}</div><div className="regional-table-wrap"><table><thead><tr><th>工资月</th><th>金额</th><th>状态</th><th>操作</th></tr></thead><tbody>{statements.map((statement) => <tr key={statement.id}><td>{statement.settlementMonth}</td><td>{yuan(statement.totalFen)}</td><td>{statement.status}</td><td>{actor.role === "admin" && statement.status === "draft" ? <button type="button" onClick={() => void run(() => client.transitionRegionalStatement(statement.id, "confirm"), "提成单已确认")}>确认</button> : null}{(actor.role === "admin" || actor.role === "finance") && statement.status === "confirmed" ? <button type="button" onClick={() => void run(() => client.transitionRegionalStatement(statement.id, "pay"), "提成单已发放")}>标记发放</button> : null}</td></tr>)}</tbody></table></div></section> : null}
      {actor.role === "admin" ? <section className="regional-section" hidden={workspace !== "templates"}><h2>提成模板</h2><div className="regional-entry-grid"><label><span>模板名称</span><input value={templateForm.name} onChange={(event) => { const name = event.currentTarget.value; setTemplateForm((value) => ({ ...value, name })); }} /></label><label><span>生效日期</span><input type="date" value={templateForm.effectiveFrom} onChange={(event) => { const effectiveFrom = event.currentTarget.value; setTemplateForm((value) => ({ ...value, effectiveFrom })); }} /></label><button type="button" onClick={() => void run(async () => { const template = await client.createRegionalTemplate({ ...templateForm, reason: "管理员新建大区提成模板" }); setTemplates((value) => [...value, template]); }, "模板草稿已创建")}>新建模板</button></div><div className="regional-table-wrap"><table><thead><tr><th>模板</th><th>版本</th><th>生效日期</th><th>状态</th><th>操作</th></tr></thead><tbody>{templates.map((template) => <tr key={template.id}><td>{template.name}</td><td>V{template.versionNo}</td><td>{template.effectiveFrom}</td><td>{template.status}</td><td>{template.status === "draft" ? <button type="button" onClick={() => void run(() => client.publishRegionalTemplate(template.id, "管理员发布"), "模板已发布")}>发布</button> : null}{template.status === "published" ? <button type="button" onClick={() => void run(() => client.assignRegionalTemplate({ managerId, templateVersionId: template.id, effectiveFrom: template.effectiveFrom, reason: "分配给大区经理" }), "模板已分配")}>分配</button> : null}</td></tr>)}</tbody></table></div></section> : null}
    </> : <div className="system-notice">{managerId ? "正在加载大区提成…" : "请选择大区经理"}</div>}
  </PageLayout>;
};
